# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MeeopMobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MeeopMobile

  target 'MeeopMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  end

  target 'MeeopMobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MeeopMobile-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MeeopMobile-tvOS

  target 'MeeopMobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
